name: Update Docker Hub Description
on:
    push:
        branches:
          - master
        paths:
          - hub/README.md
          - .github/workflows/dockerhub-description.yaml
jobs:
    dockerHubDescription:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v2
          - name: Docker Hub Description
            uses: peter-evans/dockerhub-description@v2
            with:
                username: ${{ secrets.DOCKER_HUB_USERNAME }}
                password: ${{ secrets.DOCKER_HUB_DESCRIPTION_PASS }}
                repository: dockminer/miniz
                readme-filepath: ./hub/README.md